export const kitchenList: string[] = [
  "Make mulled wine",
  "Decorate cookies",
  "Make snickerdoodles",
  "Make a hot chocolate",
  "Make Christmas cookies",
  "Make gingerbread cookies",
  "Make homemade caramel corn",
  "Make chocolate-dipped pretzels",
  "Serve a red and green themed meal",
  "Melt chocolate into Christmas molds",
];

export const outingsList: string[] = [
  "Go to the cinema",
  "Visit Santa for photos",
  "Visit a Christmas Market",
  "Book tickets to a Christmas show",
  "Buy a Christmas themed scratchcard",
  "Drive around to look at the Christmas lights",
  "Attend a Christmas parade (or watch on TV/YouTube)",
  "Go for a walk and find a natural ornament to hang at home",
  "Check out books from the library about how people celebrate Christmas in other nations",
];

export const moviesList: string[] = [
  "Watch Elf",
  "Watch Klaus",
  "Watch Scrooged",
  "Watch Die Hard",
  "Watch Bad Santa",
  "Watch Home Alone",
  "Watch The Santa Clause",
  "Watch The Polar Express",
  "Watch A Christmas Story",
  "Watch A Christmas Carol",
  "Watch A Boy Called Christmas",
  "Watch Miracle on 34th Street",
  "Watch The Muppet Christmas Carol",
  "Watch How the Grinch Stole Christmas",
  "Watch The Nightmare Before Christmas",
  "Watch National Lampoons Christmas Vacation",
];
export const craftList: string[] = [
  "Write a Christmas card",
  "Make play dough snowmen",
  "Make and mail a Christmas card to a family member or friend",
  "Make a silly Christmas video to send to friends on Christmas day",
  "Make a handmade Christmas ornament for someone else in the family",
  "Paint pinecones, or something simliar to make a centerpiece for the table",
];
export const homeList: string[] = [
  "Wrap a Christmas gift",
  "Put up more Christmas lights",
  "Make popcorn and watch a movie",
  "Have a “fancy dress” code for dinner one night",
  "YouTube funny Christmas caroling videos together",
  "Choose your favorite photos for a family yearbook",
  "Draw names and write a love note for a family member.",
  "Invite someone over for a Christmas-themed morning tea",
  "Have a living room dance party to a fun Christmas album",
  "Have a funny Christmas photo shoot (80’s Christmas sweaters?!)",
  "Use only Christmas mugs for all of your drinks for an entire day",
  "Get out a Christmas songbook and sing a few carols before bed time",
  "Celebrate Saint Nicolas Day (December 6th) by doing a secret act of kindness",
  "Everyone choose a country and then Google to see how they celebrate Christmas there",
  "Write a “new” Christmas carol, personalizing (re-writing) the words to one of your favorites",
];
